language: go

dist: trusty
sudo: false

branches:
  only:
    - master

go:
  - 1.7.3
jdk:
  - openjdk8

before_install:
  - curl https://glide.sh/get | sh
  - glide install --strip-vendor
  - go get github.com/mattn/goveralls

script:
  - make clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)
