language: go
dist: trusty
sudo: required
services:
  - docker

branches:
  only:
  - master
go:
- 1.7.3
env:
  global:
    - secure: "dbD2ERbzK4C7CAogjC6qskRQ9LYDEMWCIPJOVIugcc7PZSeKz1sPXHnd03NblgJVa5XG3r7WKbqNt3bxqkBIIuW64z7j1G1qHqNTG9jnd7Enpxt+CA/xlhAqUmIp1wkJS/m9co1mlgOfRjVoW0EmWuUK/c4omf6ZYCjKdgUwl+R9PEhRicd3g89yEu5aBW2U+aSYip8MaAuZGDCizlhTO4CoX4DkWqHee3SWqzuRJtBWg03xS3RQ8ZVNAw2RVMT9WPLQXf7l3QkA0UB3fHCLtyPc6qHwFwWF5u8hlFUYN15u3cBAVdSdaZ8v86P8SS1TiQ+9u+n2YzNwVDI2ZX4hcoXIgF2HkTkOwXvyobNh7DvcnJIWdSogSFlpLOuA5L6ggIx0W9NUUTgXIVgkGZuv5UHrq5bIbqRdCOQhz21bo3SIV3pdJ8gmJH2qmIM0oDbCv5Ge5/S8CNk2QrysRJ7qJgm5JgytNFA04xIEWQ9fbSq2Rxj2BKwpn7gdb9ZmLA60N5fduRKgydf6T8z3oTBOkfyU6ke7585zGbycZ2JQ7RjxuC9MJmNaggbPDdSWrNPBavDynGRjZP0l67FxHhVQH8CpWdCTc6V6DzHn7rfmgT4ibxKI5vC0IiBQtBy8b4Q+KkX1kKgMpmZBBuuuGuxlm5OrHY/F+gg/KM42wIBgdsI="
    - secure: "TvA0y9XD1QkvcJGHvWaiyIU7NRN9t/ZkOwwe+/HEZn40HracjNeO9ojzf7qaSsV0P5J9Pkj63Vt0nPRDzQZCTvDPUwd2/H2S9DfCZQFF5y+Yan7ZpMRRwEhCTPsizt33RGPOUd0W/TWxtU3s8j9ikjUtnMhQGmIav8w+2UrI38jjP6RZunHmvrg3nJhBVhtteV2NVrZeAdKELK/jOpNzRdzGliZoaEK+jZlAeNIePcxfA1SY2fRsjaUbCgCfV6JtZ0l6/dN/FvnjRXnnS1UHpBhwP7WNeDortOJvNMyhCTyE1ITPhD8ntJI+fjeBuwa05Oziz2MMQevpiz9xER+STfKDeM4O1/rb33n4EQtt5rGpSSm/E2EVd7meNndd5oQxGX8O+KurEbf64XRpKaEVZmXwErcZNHuO+3sJMWg+c87t9AjQd7R9RDfwWVO01kBZd1gKBJMo+HB9fo9TId5q8DfIfOODhkeeVaCydVwPL+8OBnTXjpPgoxwf6TFc3DjD2PFrtIgVh8hpELebWxrZmnE1xt0c5arUTZhzArxS3w1bHMprC0t0ezcDQYPbAjqBIQRPhWon82ncDds7eoNYUo5f72fP8IQpK27OA7er830kHPyal5omHMFAPRglrlQGB5cZU/Pxfm5y4WvakO3BYcOsREdsr6ew5etdD1pSn3o="
    - secure: "le5Nq3ENysR8W14LjvibaUICV1GdvmIbaxqD9mXLOyWDbHPG4YOlLd011Wnbheu04eES9orGyyuzDTbI56PKtHk2rySvOJPG+Fx1qs+Y54KzBIpy2Z8HNZ8fuzjg9rQmxMLs2cKt4yz4Qkqp75rQ4lruwGmdt1pu5WmMoWcGnFDhRWY2mNh0qBWN/YKxmH2Bx7NpqYBg9g4y+uAgoB9C3roU4JN5mPdXrBkOuvpH2zaCKA0RAsb6oure1ZYl0mT0+hVFfEWT8dJt7xFFk8rxPFsiRsNqcDadISFJBnjhIMyfLsHtT3lzQtg0KZJTXf5YVCWe0O37DN0ywczAW08Fxf7118m4YAjL1YjtO53kp5qDPvcTn3ogukKG2GA3DubZL0CT39JN3beE7NQfsclog/yGmwnXQvM4TZikt2D96Ycj9gEWUk97Mhwi1jhqoJc7v9njK4llVwhD433h1ET75pDY4Np4jzl6bWll6CEbE2sFeIhKv711L1aYafGqCLpwsZ5h9KN0D5nQH7L70BbihDVoDPVXrHNpai+cnfk7/h/tyNTXQljOOVr5YQeLDZL5pMvFw2TOS5ecM02MIfJCgVGlAC9/T4uKaERd+vcHMnGuRg3z+GBjhe27vCvDWY6LlaYz20b2A0yU+0NSf9X9ZBwHlOf9+7kXGn6Bo1iGuvQ="
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
- curl https://glide.sh/get | sh
- glide install --strip-vendor
- go get github.com/cloudflare/cfssl/cmd/...
- go get github.com/mattn/goveralls
script:
- make clean test
- make cross
- make DOCKER_IMAGE_TAG=${TRAVIS_TAG:-latest} docker
after_success:
- bash <(curl -s https://codecov.io/bash)
- if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -e="$DOCKER_HUB_EMAIL" -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD";
    docker push jimmidyson/pemtokeystore:${TRAVIS_TAG:-latest};
  fi
deploy:
- provider: releases
  api_key:
    secure: LoCva223NGMKfZM4DKcr1VgH46EJ6sXUhyAMDmIC2AtgUjTQLqJfT4c/dSb5pRJ9fQDNVq8jUqxgX6aGW/ioaxVZcVp+7YjjJALvRuGGSNPU6TMr+RrYYeeSco8qDmC6WBIeAB6h9Bx3gfbrrgT3zHPlMcUClRafpC6hFBvcXknVFuZAAW03k82D6+3TvO217MMG2Fv5lbhiRCwK1bhHaPl8IC95IomuGSi0LnU7bD6F4x58raAIaDG2Y0DFQ4xfNM8iwPH4nebiizlbqvOfWOct5Wu4pZlBsswKDnjokZHJh2CEo/Ls5Ljm2OiWDmCnuoF2PjJ+xudoTQ3fiITl2gaglt46EM1WOKDPWOEC0k997kWGQlrPWXhScArBkWeY11IJxV1XSxODEy83BOuf3j2SBCDZnE8xG4YRY1HBMpPhHZCrhvecOYAiH6sSSOVSIrZa9T6czlKyuj3O5kf4A/s3caMGbhDu65q5SEXP3JBMRGPqC6RsDfQ8gOwBaielJgO26haLcsZcrFUlybajEX1BPXhrJUZPluR5MQjkvRIBuYHQ7TrBrCLeQJqIDgv+gWBZ+0nYg2P9tYP6xKBmKhwUynYJKE5PynK8sMXBTfkl/6VZ4sMPWc3sL6aWBDhV9V6G/y+JHqaRq0NU/HwR1aLAmGvQjQ77jZs7uffpHlU=
  file:
    - out/pemtokeystore-darwin-amd64
    - out/pemtokeystore-linux-amd64
    - out/pemtokeystore-windows-amd64.exe
  skip_cleanup: true
  on:
    repo: jimmidyson/pemtokeystore
    tags: true
